[functions]
  directory = "netlify"
  external_node_modules = ["express", "mongoose", "zod", "bcryptjs", "dotenv"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
